# Generated by Django 5.0.2 on 2024-02-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={},
        ),
        migrations.AlterField(
            model_name='thing',
            name='due_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
