# Generated by Django 5.0.2 on 2024-02-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_thing_options_alter_thing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
