# Generated by Django 5.0.2 on 2024-02-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_producer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Film',
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
    ]
